name: Production workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        working-directory: ./client
        run: |
          npm install
          npm run build --if-present

      - name: Install the Netlify CLI
        run: npm install netlify-cli -g

      - name: List files
        run: ls

      - name: Deploy the website
        run: netlify deploy --prod --dir ./client/web-build --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}

      # - name: Deploy to netlify
      #   uses: netlify/actions/cli@master

      # - name: 
      #   working-directory: ./client
      #   run: deploy --dir=web-build --prod
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # with:
        #   args: deploy --dir=web-build --prod
