name: Production workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        working-directory: ./client
        run: |
          npm install
          npm run build --if-present

      - name: Install the Netlify CLI
        run: npm install netlify-cli -g

      - name: Deploy client
        run: netlify deploy --prod --dir ./client/web-build --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}
      
      - name: Deploy server
      - uses: akhileshns/heroku-deploy@v3.4.6 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: "fontelucas@yahoo.com.br"
          appdir: "server" 

      
